#!/bin/bash

while read line; do

    if [[ $line =~ ORF ]]; then
        echo $line
    elif [[ $line =~ LCKD ]] ; then
        continue
    elif [[ $line =~ "alt_" ]] ; then
        continue
    elif [[ $line =~ "Sky " ]] ; then
        continue
    elif [[ $line =~ "SES " ]] ; then
        continue
    elif [[ $line =~ "F3 " ]] ; then
        continue
    elif [[ $line =~ "Test" ]] ; then
        continue
    elif [[ $line =~ "TEST" ]] ; then
        continue
    elif [[ $line =~ "France" ]] ; then
        continue
    elif [[ $line =~ "QVC" ]] ; then
        continue
    elif [[ $line =~ "RT " ]] ; then
        continue
    elif [[ $line =~ "Canal " ]] ; then
        continue
    elif [[ $line =~ "CANAL " ]] ; then
        continue
    elif [[ $line =~ "CGTN" ]] ; then
        continue
    elif [[ $line =~ "Service" ]] ; then
        continue
    elif [[ ${line:43:1} = " " ]] ; then
        continue
    elif [[ ${line:43:1} = "." ]] ; then
        continue
    elif [[ $line =~ "BR " ]] ; then
        if (( !BR )); then
            echo $line
            BR=1
        else
            continue
        fi
    elif [[ $line =~ "WDR " ]] ; then
        if (( !WDR )); then
            echo $line
            WDR=1
        else
            continue
        fi
    elif [[ $line =~ "MDR " ]] ; then
        if (( !MDR )); then
            echo $line
            MDR=1
        else
            continue
        fi
    elif [[ $line =~ "NDR " ]] ; then
        if (( !NDR )); then
            echo $line
            NDR=1
        else
            continue
        fi
    elif [[ $line =~ "SWR " ]] ; then
        if (( !SWR )); then
            echo $line
            SWR=1
        else
            continue
        fi
    elif [[ $line =~ "rbb " ]] ; then
        if (( !rbb )); then
            echo $line
            rbb=1
        else
            continue
        fi
    else
        echo $line
    fi

done
