#!/bin/bash

IFS=''
tr '\0' ' ' |
while read line; do

    name="${line:43:8}${line:115:17}"

    if [[ $name =~ ^ORF ]]; then
        echo "$line"
    elif [[ $name =~ ^ATV ]] ; then
        echo "$line"
    elif [[ $name =~ ^PULS\  ]] ; then
        echo "$line"
    elif [[ $name =~ ^ServusTV\  ]] ; then
        echo "$line"
    elif [[ ${line:111:4} = "LCKD" ]] ; then
        continue
    elif [[ $name =~ "alt_" ]] ; then
        continue
    elif [[ $name =~ "Sky " ]] ; then
        continue
    elif [[ $name =~ "SES " ]] ; then
        continue
    elif [[ $name =~ "F3 " ]] ; then
        continue
    elif [[ $name =~ "Test" ]] ; then
        continue
    elif [[ $name =~ "TEST" ]] ; then
        continue
    elif [[ $name =~ "France" ]] ; then
        continue
    elif [[ $name =~ "QVC" ]] ; then
        continue
    elif [[ $name =~ "RT " ]] ; then
        continue
    elif [[ $name =~ "Canal " ]] ; then
        continue
    elif [[ $name =~ "CANAL " ]] ; then
        continue
    elif [[ $name =~ "CGTN" ]] ; then
        continue
    elif [[ $name =~ "Service" ]] ; then
        continue
    elif [[ $name =~ "14.12.2021" ]] ; then
        continue
    elif [[ ${name:0:1} = " " ]] ; then
        continue
    elif [[ $name =~ ^\. ]] ; then
        continue
    elif [[ $name =~ "BR " ]] ; then
        if (( !BR )); then
            echo "$line"
            BR=1
        else
            continue
        fi
    elif [[ $name =~ "WDR " ]] ; then
        if (( !WDR )); then
            echo "$line"
            WDR=1
        else
            continue
        fi
    elif [[ $name =~ "MDR " ]] ; then
        if (( !MDR )); then
            echo "$line"
            MDR=1
        else
            continue
        fi
    elif [[ $name =~ "NDR " ]] ; then
        if (( !NDR )); then
            echo "$line"
            NDR=1
        else
            continue
        fi
    elif [[ $name =~ "SWR " ]] ; then
        if (( !SWR )); then
            echo "$line"
            SWR=1
        else
            continue
        fi
    elif [[ $name =~ "rbb " ]] ; then
        if (( !rbb )); then
            echo "$line"
            rbb=1
        else
            continue
        fi
    else
        echo "$line"
    fi

done
